### ISSUE TITLE
The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first

### ISSUE THREAD

**Issue by eddydn** [mukeshsolanki/social-login-helper#1]
I have setup all like your example but i get error : 

The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first

Also i have put app id in Manifest xml

**Comment by mukeshsolanki** [comment]
This issue generally occurs when you forget to add the Facebook app id in the manifest file. Can you please double check and let me know

**Comment by mukeshsolanki** [comment]
Hey have you been able to test it?? Is everything working fine? If so then can we close this issue??

**Comment by mukeshsolanki** [comment]
no response closing issue

**Comment by qomarullah** [comment]
Same issue, got error: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first
solved by add
```javascript
FacebookSdk.setApplicationId(getString(R.string.facebook_app_id));
        //initialize Facebook SDK
        FacebookSdk.sdkInitialize(getApplicationContext());
        if (BuildConfig.DEBUG) {
            FacebookSdk.setIsDebugEnabled(true);
            FacebookSdk.addLoggingBehavior(LoggingBehavior.INCLUDE_ACCESS_TOKENS);
        }
```

**Comment by vamsigp** [comment]
FacebookSdk.sdkInitialize() is deprecated from SDK V4 onwards.

**Comment by liujett** [comment]
add in where?which file and the location? @qomarullah

**Comment by Aashir1** [comment]
Having same issue in react native this is a screen shot of the error.
![screenshot_2018-03-12-23-00-02-75](https://user-images.githubusercontent.com/25276195/37301349-2203d438-264a-11e8-9c7d-bdb10e2199a9.png)

**Comment by Bhavdip** [comment]
In my case, I can able to execute successfully doing the below:

  ```
@Override
  public void onCreate() {
    super.onCreate();
    FacebookSdk.setApplicationId("12312312323123");
    FacebookSdk.sdkInitialize(this);
    AppEventsLogger.activateApp(this);
    SoLoader.init(this, /* native exopackage */ false);
  }
```

**Comment by Bhavdip** [comment]
```@Override  public void onCreate() {    super.onCreate();    FacebookSdk.setApplicationId("12312312323123");    FacebookSdk.sdkInitialize(this);    AppEventsLogger.activateApp(this);    SoLoader.init(this, /* native exopackage */ false);  }```

**Comment by Bhavdip** [comment]
```@Override  public void onCreate() {    super.onCreate();    FacebookSdk.setApplicationId("12312312323123");    FacebookSdk.sdkInitialize(this);    AppEventsLogger.activateApp(this);    SoLoader.init(this, /* native exopackage */ false);  }```

**Comment by gurmundi7** [comment]
Thanks @Bhavdip. It worked for me. 

My mistake was writing 
`AppEventsLogger.activateApp(this);` 
after 
`SoLoader.init(this, /* native exopackage */ false); `
