### ISSUE TITLE
Problem in gradle sync due to Twitter SDK

### ISSUE THREAD

**Issue by rahul260792** [mukeshsolanki/social-login-helper#2]
As soon as I add  compile 'com.github.mukeshsolanki:social-login-helper:1.0.2' in my build.gradle(Module:app) and sync the gradle it throws the following error:

**Error:Failed to resolve: com.twitter.sdk.android:twitter:2.3.2**

**Comment by mukeshsolanki** [comment]
can you test using the sample project.

**Comment by mukeshsolanki** [comment]
no response issue closed
